CREATE TABLE ${WMADATA_SCHEMA_NAME}.nhdflowline_network
(
    objectid SERIAL,
    comid integer,
    fdate timestamp with time zone,
    resolution character varying COLLATE pg_catalog."default",
    gnis_id character varying COLLATE pg_catalog."default",
    gnis_name character varying COLLATE pg_catalog."default",
    lengthkm double precision,
    reachcode character varying COLLATE pg_catalog."default",
    flowdir character varying COLLATE pg_catalog."default",
    wbareacomi integer,
    ftype character varying COLLATE pg_catalog."default",
    fcode integer,
    shape_length double precision,
    streamleve double precision,
    streamorde double precision,
    streamcalc double precision,
    fromnode double precision,
    tonode double precision,
    hydroseq double precision,
    levelpathi double precision,
    pathlength double precision,
    terminalpa double precision,
    arbolatesu double precision,
    divergence double precision,
    startflag double precision,
    terminalfl double precision,
    dnlevel double precision,
    uplevelpat double precision,
    uphydroseq double precision,
    dnlevelpat double precision,
    dnminorhyd double precision,
    dndraincou double precision,
    dnhydroseq double precision,
    frommeas double precision,
    tomeas double precision,
    rtndiv double precision,
    vpuin double precision,
    vpuout double precision,
    areasqkm double precision,
    totdasqkm double precision,
    divdasqkm double precision,
    tidal double precision,
    totma double precision,
    wbareatype character varying COLLATE pg_catalog."default",
    pathtimema double precision,
    hwnodesqkm double precision,
    maxelevraw double precision,
    minelevraw double precision,
    maxelevsmo double precision,
    minelevsmo double precision,
    slope double precision,
    elevfixed character varying COLLATE pg_catalog."default",
    hwtype character varying COLLATE pg_catalog."default",
    slopelenkm real,
    qa_ma double precision,
    va_ma double precision,
    qc_ma double precision,
    vc_ma double precision,
    qe_ma double precision,
    ve_ma double precision,
    qa_01 double precision,
    va_01 double precision,
    qc_01 double precision,
    vc_01 double precision,
    qe_01 double precision,
    ve_01 double precision,
    qa_02 double precision,
    va_02 double precision,
    qc_02 double precision,
    vc_02 double precision,
    qe_02 double precision,
    ve_02 double precision,
    qa_03 double precision,
    va_03 double precision,
    qc_03 double precision,
    vc_03 double precision,
    qe_03 double precision,
    ve_03 double precision,
    qa_04 double precision,
    va_04 double precision,
    qc_04 double precision,
    vc_04 double precision,
    qe_04 double precision,
    ve_04 double precision,
    qa_05 double precision,
    va_05 double precision,
    qc_05 double precision,
    vc_05 double precision,
    qe_05 double precision,
    ve_05 double precision,
    qa_06 double precision,
    va_06 double precision,
    qc_06 double precision,
    vc_06 double precision,
    qe_06 double precision,
    ve_06 double precision,
    qa_07 double precision,
    va_07 double precision,
    qc_07 double precision,
    vc_07 double precision,
    qe_07 double precision,
    ve_07 double precision,
    qa_08 double precision,
    va_08 double precision,
    qc_08 double precision,
    vc_08 double precision,
    qe_08 double precision,
    ve_08 double precision,
    qa_09 double precision,
    va_09 double precision,
    qc_09 double precision,
    vc_09 double precision,
    qe_09 double precision,
    ve_09 double precision,
    qa_10 double precision,
    va_10 double precision,
    qc_10 double precision,
    vc_10 double precision,
    qe_10 double precision,
    ve_10 double precision,
    qa_11 double precision,
    va_11 double precision,
    qc_11 double precision,
    vc_11 double precision,
    qe_11 double precision,
    ve_11 double precision,
    qa_12 double precision,
    va_12 double precision,
    qc_12 double precision,
    vc_12 double precision,
    qe_12 double precision,
    ve_12 double precision,
    lakefract double precision,
    surfarea double precision,
    rareahload double precision,
    rpuid character varying COLLATE pg_catalog."default",
    vpuid character varying COLLATE pg_catalog."default",
    enabled smallint DEFAULT 1,
    the_geom geometry(MultiLineStringZM,4269) NOT NULL,
    CONSTRAINT nhdflowline_network_pkey PRIMARY KEY (objectid)
)
WITH (
    OIDS = FALSE
);